name: Run Prediction Script

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  run_prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install statsmodels

    - name: Run prediction script
      run: |
        python main.py

    - name: Run prediction script
      run: |
        python main.py

    - name: Stage changes
      run: git add data/history.json data/predicted.json data/stable.json
      id: git_add

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit"
          echo "::set-output name=changes::false"
        else
          echo "Changes detected"
          echo "::set-output name=changes::true"
        fi

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add data/history.json data/predicted.json data/stable.json
        git commit -m "Update predictions"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
